#!/bin/bash 

M4A_128=140

OPUS_50=249
OPUS_70=250
OPUS_160=251

AVC_720p30=136
AVC_720p60=298
AVC_1080p30=137
AVC_1080p60=299

VP9_1080p30=248
VP9_1080p60=303
VP9_1440p30=271
VP9_1440p60=308
VP9_2160p30=313
VP9_2160p60=315

BEST_M4A="bestaudio[ext=m4a]"
BEST_MP4="bestvideo[ext=mp4]"
BEST_WEBM="bestvideo[ext=webm]"

VP9_1080p60="248+251"
VP9_1080p60="248+251"

WEBM_720_OPUS_160="247+251"
MP4_1080_OPUS_160="247+251"

if [ "$1" = "best_webm" ]; then
    format="$BEST_WEBM+$OPUS_160/$BEST_WEBM+$OPUS_70/$BEST_WEBM+$OPUS_50"
elif [ "$1" = "best_mp4" ]; then
    format="$BEST_MP4+$BEST_M4A"
elif [ "$1" = "best" ]; then
    format="$BEST_WEBM+$OPUS_160/$BEST_WEBM+$OPUS_70/$BEST_WEBM+$OPUS_50/$BEST_MP4+$BEST_M4A"
else
    >&2 echo "Usage: channel-dl <best_webm|best_mp4|best> [youtube-dl args...]"
fi

args=( "$@" )

youtube-dl -f "$format" -o "%(title)s (%(id)s) [%(vcodec)s %(height)dp] [%(acodec)s %(abr)dkbps].%(ext)s" ${args[@]:1}
