#!/bin/bash
rm -rf "$HOME/.cache_old/"
rm -rf "$HOME/.cache/"

rm -rf "$HOME/.config/Riot/Cache/"
rm -rf "$HOME/.config/discord/Cache/"
rm -rf "$HOME/.config/Slack/Cache/"

rm -f "$HOME/.local/share/baloo/index"
