#!/usr/bin/python3 

import sys
import math

if __name__ == "__main__":
    matrix = [float(arg) for sys.argv[1:]]
    rows = math.sqrt(len(matrix))
    for i in range(rows):
        for j in range(rows):
            
