#!/bin/bash

# Lists all pingable IPs on the local network.

PING_COUNT=1
TIMEOUT_SECONDS=1

function is_alive_ping {
    ping -q -c $PING_COUNT -W $TIMEOUT_SECONDS "$1" &> /dev/null
    
    if [[ $? == 0 ]]; then
        printf '%s is up\n' "$i"
    fi
}

for i in 192.168.0.{1..255}; do
    is_alive_ping $i &
done

wait
