#!/usr/bin/python3

import sys
import math
from math import *

def preprocess(expression):
    expression = expression.replace("¹", "**1")
    expression = expression.replace("²", "**2")
    expression = expression.replace("³", "**3")
    expression = expression.replace("⁴", "**4")
    expression = expression.replace("⁵", "**5")
    expression = expression.replace("⁶", "**6")
    expression = expression.replace("⁷", "**7")
    expression = expression.replace("⁸", "**8")
    expression = expression.replace("⁹", "**9")
    expression = expression.replace("½", "0.5")
    expression = expression.replace("¼", "0.25")
    return expression

def isum(*args):
    result=0
    for arg in args:
        result += 1 / arg
    return 1 / result

if __name__ == "__main__":
    if len(sys.argv) < 2:
        exit(0)
    
    expression = " ".join(sys.argv[1:])
    result = eval(preprocess(expression))
    if isinstance(result, float):
        int_result=int(result)
        if result == int_result:
            result=int_result
    
    print(result)
