#!/usr/bin/python

import sys
import random
from random import randint

if __name__ == "__main__":
    minnum = int(sys.argv[1]) if len(sys.argv) > 2 else 1
    maxnum = int(sys.argv[2]) if len(sys.argv) > 2 else int(sys.argv[1]) if len(sys.argv) > 1 else 6
    print(randint(minnum, maxnum))
    
