#!/usr/bin/python3

"""
Applies the ROT encryption algorithm to input read from stdin.
(commonly known as Caesar Cipher)

This will shift all alphabetic characters by the given rotation.
Case is preserved by this operation.

All digits and other non-alphabetic characters are not affected by the rotation.
Usage: rot <rotation>
"""

import sys

def do_rot(c, rot):
    c = ord(c)
    if c >= ord('A') and c <= ord('Z'):
        result = (c + rot) % 91
        if result < ord('A'):
            result += ord('A')
        return chr(result)
    elif c >= ord('a') and c <= ord('z'):
        result = (c + rot) % 123
        if result < ord('a'):
            result += ord('a')
        return chr(result)
    else:
        return chr(c)

if __name__ == "__main__":
    rot = int(sys.argv[1]) % 26 if len(sys.argv) > 1 else 3
    for line in sys.stdin:
        for c in line:
            sys.stdout.write(do_rot(c, rot))
