#!/usr/bin/python3

import sys

if __name__ == "__main__":
    rot = int(sys.argv[1]) % 26
    for line in sys.stdin:
        for c in line:
            c = ord(c)
            # char = c if not c.isalpha() else (c + rot) % 91 + 65 if c >= 'a' else (c + rot) % 123 + 97
            if c >= ord('A') and c <=ord('Z'):
                result = (c + rot) % 91
                if result <= ord('A'):
                    result += ord('A')
            elif c >= ord('a') and c <= ord('z'):
                result = (c + rot) % 123
                if result <= ord('a'):
                    result += ord('a')
            else:
                result = c

            sys.stdout.write(chr(result))
