#!/bin/bash
rm -rf "$HOME/.cache_old/"
rm -rf "$HOME/.cache/"

rm -rf "$HOME/.config/Riot/Cache/"
rm -rf "$HOME/.config/discord/Cache/"
rm -rf "$HOME/.config/Slack/Cache/"

rm -f "$HOME/.local/share/baloo/index"

#rm -f "$HOME/.kde/share/apps/amarok/mysqle/ib_logfile0"
#rm -f "$HOME/.kde/share/apps/amarok/mysqle/ib_logfile1"
