#!/bin/bash
src_ext=.$1

if test -z "$1" || test -z "$2"; then
    >&2 echo "Usage: $(basename "$0") <source extension> <target extension>"
    exit
fi

#for f in *$src_ext; do echo "$f"; echo "${f%$src_ext}.$2"; done
for f in *$src_ext; do
    mv "$f" "${f%$src_ext}.$2"
done
