#!/bin/bash

echoerr=">&2 echo"

# if not-empty; then
#     eval $echoerr Working directory must be empty!
#     exit 1
# fi

#if [ -n "$1" ]; then
#    codec=$1
#else
#    codec=aac
# fi
codec=$1

if [ $codec = "opus" ]; then
    ext=webm
    ideal=251
elif [ codec = "aac" ]; then
    ext=m4a
    ideal=140
fi 

# f: format
# o: output
# i, --ignore-errors: continue download on errors
# --playlist-start: playlist start or default 1
args=( "$@" )
youtube-dl $2 -f ${ideal}/bestaudio[ext=$ext] -o "%(title)s (%(id)s) [%(acodec)s %(abr)dkbps].%(ext)s" --extract-audio --audio-format "$codec" ${args[@]:2}

for source in *; do
    #source="${f%.playlist_dl}"
    #mv "$f" "$source"
    
    # omit the additional information about codec and audio bitrate from the thumbnail titles
    if [[ $source == *.jpg ]]; then
        target="${source% [*}.jpg"
        
        # if pre-existing .jpg files were in the directory, these would be falsely just renamed to .jpg.jpg
        if [[ $target != *.jpg.jpg ]]; then
            mv "$source" "$target";
        fi
        
    # if the file has been saved as ".opus" by youtube-dl, rename it to .oga
    elif [[ $source == *.opus ]]; then
        #ffmpeg -i "$source" -c:a copy "${source%.*}.oga"
        mv "$source" "${source%.opus}.oga"
    fi
done
